services:
  ollama:
    build:
      context: ./ollama-custom
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/" ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s

  database:
    build:
      context: ./mongodb-custom
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  qdrant:
    build:
      context: ./qdrant-custom
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6333/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: ./demo-back
      dockerfile: Dockerfile
      secrets:
          - hf_token
    depends_on:
      database:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy

  frontend:
    ports:
      - 3000:3000
    build:
      context: ./demo-front
      dockerfile: Dockerfile
    depends_on:
      - backend

volumes:
  mongodb_data:
  qudrant_data:
  ollama_data:

secrets:
  hf_token:
    environment: HF_TOKEN
  

