site_name: Chatty
repo_url: https://github.com/CITIUS-iRiA-eRisk/demo-inside-the-lab
repo_name: CITIUS-iRiA-eRisk/demo-inside-the-lab
edit_uri: edit/main/docs/


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
        primary: teal
        accent: lime

  logo: icons/loro.png
  favicon: icons/loro.png
  code:
    highlight_theme: monokai
nav:
  - Home: index.md
  - Installation: installation.md
  - Prerequisites: requirements.md
  - Usage: usage.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  
plugins:
    - mkdocs-video

copyright: |
  &copy; 2025 <a href="https://github.com/CITIUS-iRiA-eRisk/demo-inside-the-lab"  target="_blank" rel="noopener">Manuel Couto Pintos</a>