import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '../../components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, context
}: {
  children: React.ReactNode,
  context: any
}) {


  return (
    <html className='h-full w-full' lang="en">
      
      <body className={`h-full w-full relative group ${inter.className}`}>
        <div className="w-full h-full  absolute lg:bg-gray-200 lg:p-4 lg:dark:bg-slate-950/30 flex place-items-center before:absolute 
            before:h-[400px] before:w-[480px] before:-translate-x-1/3 before:rounded-full before:bg-gradient-radial
            before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 
            after:h-[280px] after:w-[240px] after:translate-x-3/4 after:bg-gradient-conic after:from-sky-200 
            after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br 
            before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 
            after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] justify-center -inset-1 pointer-events-none"></div>
        <div className='w-full h-full  z-40'>
          
          <div className='h-[80px] w-full p-3'>
            <NavBar />
          </div>

          <div className='h-[calc(100%-80px)] w-full flex p-2 items-start justify-center '>
            <div className="h-full w-full">
              {children}
            </div>
          </div>

        </div>
      </body>
    </html>
  )
}


